name: Deploy HRAE Website

on:
  push:
    branches:
      - main   # Déploiement automatique à chaque push sur main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Copy deploy script to VPS
        run: scp -o StrictHostKeyChecking=no deploy.sh root@72.61.101.174:/var/www/hrae-webSite/deploy.sh

      - name: Make script executable
        run: ssh -o StrictHostKeyChecking=no root@72.61.101.174 "chmod +x /var/www/hrae-webSite/deploy.sh"

      - name: Deploy to VPS
        run: ssh -o StrictHostKeyChecking=no root@72.61.101.174 "/var/www/hrae-webSite/deploy.sh"
